
public_option_optionacocherreserve_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BenskiReservationBundle:Option/PublicOptionACocherReserve:edit" }

public_option_optionacocherreserve_update:
    pattern:  /{id}/update
    defaults: { _controller: "BenskiReservationBundle:Option/PublicOptionACocherReserve:update" }
    requirements: { _method: post|put }

