news:
    pattern:  /
    defaults: { _controller: "BenskiNewsBundle:News:index" }

news_show:
    pattern:  /{id}/show
    defaults: { _controller: "BenskiNewsBundle:News:show" }

news_new:
    pattern:  /new
    defaults: { _controller: "BenskiNewsBundle:News:new" }

news_create:
    pattern:  /create
    defaults: { _controller: "BenskiNewsBundle:News:create" }
    requirements: { _method: post }

news_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BenskiNewsBundle:News:edit" }

news_update:
    pattern:  /{id}/update
    defaults: { _controller: "BenskiNewsBundle:News:update" }
    requirements: { _method: post|put }

news_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BenskiNewsBundle:News:delete" }
    requirements: { _method: post|delete }
