<?php

namespace Benski\CatalogueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartementRepository extends EntityRepository
{
}
