<?php

namespace Benski\CatalogueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SejourAppartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SejourAppartementRepository extends EntityRepository
{
}
