<?php

namespace Benski\CatalogueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SejourAppartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SejourAppartementRepository extends EntityRepository {

   public function myFindByAppartementAndSejour($sejour, $appartement) {
      //$qb = $this->createQueryBuilder('sa');
      //$qb->where('where', $qb->expr()->andx(
      //$qb->expr()->eq('sa.appartement', ':appartement'),
      //$qb->expr()->like('sa.sejour', ':sejour'))    );

      $qb = $this->getEntityManager()->createQuery('SELECT sa 
         FROM BenskiCatalogueBundle:SejourAppartement sa 
         WHERE sa.appartement = :appartement 
         AND sa.sejour = :sejour');

      $qb->setParameter('appartement', $appartement);
      $qb->setParameter('sejour', $sejour);

      // On récupère la Query à partir du QueryBuilder

      // On récupère les résultats à partir de la Query
      $resultats = $qb->getSingleResult();

      // On retourne ces résultats
      return $resultats;
   }

}
