## YAML Template.

user_admin:
    pattern:  /
    defaults: { _controller: "BenskiUserBundle:User:index" }
    
user_list:
    pattern:  /
    defaults: { _controller: "BenskiUserBundle:User:index" }


user_admin_show:
    pattern:  /{id}/show
    defaults: { _controller: "BenskiUserBundle:User:show" }

user_admin_new:
    pattern:  /new
    defaults: { _controller: "BenskiUserBundle:User:new" }

user_admin_create:
    pattern:  /create
    defaults: { _controller: "BenskiUserBundle:User:create" }
    requirements: { _method: post }

user_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BenskiUserBundle:User:edit" }

user_admin_update:
    pattern:  /{id}/update
    defaults: { _controller: "BenskiUserBundle:User:update" }
    requirements: { _method: post|put }

user_admin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BenskiUserBundle:User:delete" }
    requirements: { _method: post|delete }
