<?php

namespace Benski\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppartementReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartementReserveRepository extends EntityRepository
{
}
