<?php

namespace Benski\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationSejourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationSejourRepository extends EntityRepository
{
}
