<?php

namespace Benski\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SejourReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SejourReserveRepository extends EntityRepository
{
    public function findAllJoined(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT s FROM BenskiReservationBundle:SejourReserve s "
                . "JOIN s.reservation r");
        return $query->getResult(); 
    }
}
