benski_reservation:
    resource: "@BenskiReservationBundle/Resources/config/routing.yml"
    prefix:   /

benski_news:
    resource: "@BenskiNewsBundle/Resources/config/routing.yml"
    prefix:   /

benski_common:
    resource: "@BenskiCommonBundle/Resources/config/routing.yml"
    prefix:   /

benski_catalogue:
    resource: "@BenskiCatalogueBundle/Resources/config/routing.yml"
    prefix:   /
    


# -- FOS -- #

benski_user_bundle:
    resource: "@BenskiUserBundle/Resources/config/routing.yml"
    prefix:   /
    