benski_common:
    resource: "@BenskiCommonBundle/Resources/config/routing.yml"
    prefix:   /

benski_catalogue:
    resource: "@BenskiCatalogueBundle/Resources/config/routing.yml"
    prefix:   /



