BenskiCatalogueBundle_sejour:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/sejour.yml"
        prefix:   /sejour


BenskiCatalogueBundle_appartement:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/appartement.yml"
        prefix:   /appartement
