BenskiCatalogueBundle_sejour:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/sejour.yml"
        prefix:   /sejour


BenskiCatalogueBundle_appartement:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/appartement.yml"
        prefix:   /appartement

BenskiCatalogueBundle_destination:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/destination.yml"
        prefix:   /destination

BenskiCatalogueBundle_sejour_appartement:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/sejour_appartement.yml"
        prefix:   /sejourappartement

BenskiCatalogueBundle_option:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/abstractoption.yml"
        prefix:   /option
        
BenskiCatalogueBundle_optionchoixmultiple:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/optionchoixmultiple.yml"
        prefix:   /optionchoixmultiple
        
BenskiCatalogueBundle_optionacocher:
        resource: "@BenskiCatalogueBundle/Resources/config/routing/option_optionacocher.yml"
        prefix:   /optionacocher