parameters:
#    news.example.class: Benski\NewsBundle\Example

services:
    benski_user.registration.form.type:
        class: Benski\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: benski_user_registration }
