parameters:
#    benski_user.example.class: Benski\UserBundle\Example

services:
#    benski_user.example:
#        class: %benski_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
