parameters:
#    benski_common.example.class: Benski\CommonBundle\Example

services:
#    benski_common.example:
#        class: %benski_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
