parameters:
#    benski_content.example.class: Benski\ContentBundle\Example

services:
#    benski_content.example:
#        class: %benski_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
