<?php

namespace Benski\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionedObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionedObjectRepository extends EntityRepository
{
}
