<?php

namespace Benski\ReservationBundle\Entity\Option;

use Doctrine\ORM\EntityRepository;

/**
 * OptionChoixMultipleReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionChoixMultipleReserveRepository extends EntityRepository
{
}
