<?php

namespace Benski\ReservationBundle\Entity\Option;

use Doctrine\ORM\EntityRepository;

/**
 * OptionACocherReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionACocherReserveRepository extends EntityRepository
{
}
