<?php

namespace Benski\ReservationBundle\Entity\Option;

use Doctrine\ORM\EntityRepository;

/**
 * OptionReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionReserveRepository extends EntityRepository
{
}
