parameters:
#    benski_website.example.class: Benski\WebsiteBundle\Example

services:
#    benski_website.example:
#        class: %benski_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
