pack:
    pattern:  /
    defaults: { _controller: "BenskiCatalogueBundle:Pack:index" }

pack_show:
    pattern:  /{id}/show
    defaults: { _controller: "BenskiCatalogueBundle:Pack:show" }

pack_new:
    pattern:  /new
    defaults: { _controller: "BenskiCatalogueBundle:Pack:new" }

pack_create:
    pattern:  /create
    defaults: { _controller: "BenskiCatalogueBundle:Pack:create" }
    requirements: { _method: post }

pack_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BenskiCatalogueBundle:Pack:edit" }

pack_update:
    pattern:  /{id}/update
    defaults: { _controller: "BenskiCatalogueBundle:Pack:update" }
    requirements: { _method: post|put }

pack_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BenskiCatalogueBundle:Pack:delete" }
    requirements: { _method: post|delete }
    
pack_bind_option_form:
    pattern: /{packId}/bind/option
    defaults: { _controller: "BenskiCatalogueBundle:Pack:bindOptionForm" }
    
pack_bind_option_create:
    pattern: /{packId}/bind/option/{id}
    defaults: { _controller: "BenskiCatalogueBundle:Pack:createBindOption" }
