<?php

namespace Benski\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository {

    public function getNews($nombreParPage = 10, $page) {
        if ($page < 1) {
            throw new \InvalidArgumentException('L\'argument $page ne peut
être inférieur à 1 (valeur : "' . $page . '").');
        }


        $query = $this->getEntityManager()->createQuery('
            SELECT n, a FROM BenskiContentBundle:News n
            JOIN n.article a
            ORDER BY a.dateCreation DESC');
        $query  ->setFirstResult(($page-1) * $nombreParPage)
                ->setMaxResults($nombreParPage);
        return new Paginator($query);
    }

}
