parameters:
#    benski_reservation.example.class: Benski\ReservationBundle\Example

services:
#    benski_reservation.example:
#        class: %benski_reservation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
