<?php

namespace Benski\CatalogueBundle\Entity\Option;

use Doctrine\ORM\EntityRepository;

/**
 * OptionACocherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionACocherRepository extends EntityRepository
{
}
