<?php

namespace Benski\CatalogueBundle\Entity\Option;

use Doctrine\ORM\EntityRepository;

/**
 * OptionChoixMultipleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionChoixMultipleRepository extends EntityRepository
{
}
